version: "3.9"

services:
  postgres:
    container_name: d3k-postgres-server
    image: docker.io/library/postgres:15-alpine
    # restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD?"DB_PASSWORD not set."}
      POSTGRES_USER: ${DB_USERNAME?"DB_USERNAME not set."}
      # POSTGRES_DB: ${DB_DATABASE_NAME?"DB_DATABASE_NAME not set."}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net-one
    # expose:
    #     - "5432"

  redis:
    profiles:
      - disabled
    container_name: d3k-redis-server
    image: redis:7-alpine
    # restart: unless-stopped
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - net-one
    # expose:
    #     - "6379"

  flyway:
    image: docker.io/flyway/flyway:9.18-alpine
    container_name: flyway
    profiles:
      - tools
    network_mode: host
    # restart: unless-stopped
    volumes:
      - ..:/flyway/conf:ro
      - ./migrations/:/flyway/sql:ro
    environment:
      # FIXME: podman-compose doesn't support recursive variable expansion
      FLYWAY_URL: ${FLYWAY_URL?"FLYWAY_URL var not found"}
      # FLYWAY_URL: ${FLYWAY_URL:-jdbc:postgresql://localhost:5432/${DB_USERNAME?"DB_USERNAME not set."\}?user=${DB_USERNAME?"DB_USERNAME not set."\}&password=${DB_PASSWORD?"DB_PASSWORD not set."\}}
      # FLYWAY_URL: ${FLYWAY_URL:-jdbc:postgresql://localhost:5432/d3k?user=d3k&password=password}


networks:
  net-one:

volumes:
  redisdata:
  pgdata:
